### ISSUE TITLE
DOMException on audio capture stop

### ISSUE THREAD

**Issue by klausj** [IPS-LMU/WebSpeechRecorderNg#10]
Traffic light stuck in state "yellow". Start button is enabled.
Exception:

main.21a8081f09f3d357797c.js:1 ERROR DOMException: Failed to execute 'disconnect' on 'AudioNode': the given destination is not connected.
    at t.stop (https://webapptest.phonetik.uni-muenchen.de/corpusmachine/lib/ng/main.21a8081f09f3d357797c.js:1:119602)
    at t.stopRecording (https://webapptest.phonetik.uni-muenchen.de/corpusmachine/lib/ng/main.21a8081f09f3d357797c.js:1:362131)
    at https://webapptest.phonetik.uni-muenchen.de/corpusmachine/lib/ng/main.21a8081f09f3d357797c.js:1:361943
    at e.invokeTask (https://webapptest.phonetik.uni-muenchen.de/corpusmachine/lib/ng/polyfills.5a3191e5de5068185cf8.js:1:7964)
    at Object.onInvokeTask (https://webapptest.phonetik.uni-muenchen.de/corpusmachine/lib/ng/main.21a8081f09f3d357797c.js:1:29653)
    at e.invokeTask (https://webapptest.phonetik.uni-muenchen.de/corpusmachine/lib/ng/polyfills.5a3191e5de5068185cf8.js:1:7885)
    at t.runTask (https://webapptest.phonetik.uni-muenchen.de/corpusmachine/lib/ng/polyfills.5a3191e5de5068185cf8.js:1:3142)
    at t.invokeTask (https://webapptest.phonetik.uni-muenchen.de/corpusmachine/lib/ng/polyfills.5a3191e5de5068185cf8.js:1:9074)
    at invoke (https://webapptest.phonetik.uni-muenchen.de/corpusmachine/lib/ng/polyfills.5a3191e5de5068185cf8.js:1:8962)
    at n.args.(anonymous function) (https://webapptest.phonetik.uni-muenchen.de/corpusmachine/lib/ng/polyfills.5a3191e5de5068185cf8.js:1:25253)
Zt @ main.21a8081f09f3d357797c.js:1
t.handleError @ main.21a8081f09f3d357797c.js:1
next @ main.21a8081f09f3d357797c.js:1
e.object.i @ main.21a8081f09f3d357797c.js:1
e.__tryOrUnsub @ main.21a8081f09f3d357797c.js:1
e.next @ main.21a8081f09f3d357797c.js:1
e._next @ main.21a8081f09f3d357797c.js:1
e.next @ main.21a8081f09f3d357797c.js:1
e.next @ main.21a8081f09f3d357797c.js:1
e.emit @ main.21a8081f09f3d357797c.js:1
(anonymous) @ main.21a8081f09f3d357797c.js:1
e.invoke @ polyfills.5a3191e5de5068185cf8.js:1
t.run @ polyfills.5a3191e5de5068185cf8.js:1
t.runOutsideAngular @ main.21a8081f09f3d357797c.js:1
onHandleError @ main.21a8081f09f3d357797c.js:1
e.handleError @ polyfills.5a3191e5de5068185cf8.js:1
t.runTask @ polyfills.5a3191e5de5068185cf8.js:1
t.invokeTask @ polyfills.5a3191e5de5068185cf8.js:1
invoke @ polyfills.5a3191e5de5068185cf8.js:1
n.args.(anonymous function) @ polyfills.5a3191e5de5068185cf8.js:1
setTimeout (async)
u @ polyfills.5a3191e5de5068185cf8.js:1
e.scheduleTask @ polyfills.5a3191e5de5068185cf8.js:1
onScheduleTask @ polyfills.5a3191e5de5068185cf8.js:1
e.scheduleTask @ polyfills.5a3191e5de5068185cf8.js:1
t.scheduleTask @ polyfills.5a3191e5de5068185cf8.js:1
t.scheduleMacroTask @ polyfills.5a3191e5de5068185cf8.js:1
(anonymous) @ polyfills.5a3191e5de5068185cf8.js:1
o.(anonymous function) @ polyfills.5a3191e5de5068185cf8.js:1
t.pauseItem @ main.21a8081f09f3d357797c.js:1
navigator.mediaDevices.ac.transportActions.pauseAction.onAction @ main.21a8081f09f3d357797c.js:1
t.perform @ main.21a8081f09f3d357797c.js:1
(anonymous) @ main.21a8081f09f3d357797c.js:1
handleEvent @ main.21a8081f09f3d357797c.js:1
handleEvent @ main.21a8081f09f3d357797c.js:1
fr @ main.21a8081f09f3d357797c.js:1
(anonymous) @ main.21a8081f09f3d357797c.js:1
(anonymous) @ main.21a8081f09f3d357797c.js:1
e.invokeTask @ polyfills.5a3191e5de5068185cf8.js:1
onInvokeTask @ main.21a8081f09f3d357797c.js:1
e.invokeTask @ polyfills.5a3191e5de5068185cf8.js:1
t.runTask @ polyfills.5a3191e5de5068185cf8.js:1
t.invokeTask @ polyfills.5a3191e5de5068185cf8.js:1
p @ polyfills.5a3191e5de5068185cf8.js:1
h @ polyfills.5a3191e5de5068185cf8.js:1

**Comment by klausj** [comment]
Happens when the max recording timer stops recording while the postrecording timer is active and stops recording twice when timed out. If max recording timer times out it must cancel the post recording timer.
